### PR TITLE
EM & CI Overlays

### PR DESCRIPTION
**Pull request by c2nelson**
@vwilliamsn i'd like to discuss several things.

### CODE REVIEW

**Comment by vwilliamsn** [comment]
@c2nelson - here are my edits for the CI overlay.  The Telehealth overlay has a question that's not in an accordion folder, so I think we can keep the CI overlay relatively the same.  Let's make some changes to some of the questions (H2 headings) and make them statements (H2), see below.

- Community Based Services
- Community Based Settings
- Segregated Settings
- No changes to Q4 (When are community-based services “appropriate”?)
- No changes to Q5 (What does it mean to “not oppose” community based services?)
- Q6 reasonable accommodation question into an accordion folder.
- A Right to Community Intergration

Happy to chat if you have any questions/concerns. Thanks!

**Comment by vwilliamsn** [comment]
@c2nelson - here are my edits for the EM overlay.

*Capitalize the first letters of each word, except 'and' (see below):
- Emergency alerts
- Community evacuation and transportation
- Emergency shelter programs

*2nd bullet under Emergency Alert, add period (.) at end of sentence

*3rd bullet under Physical Accessibility at Shelters, capitalize the first letter of each word, take out the punctuation & 'and'

**Review by vwilliamsn — APPROVED** [review]
CI overlay is approved! Great job @c2nelson and thanks for all your work on this.

**Comment by c2nelson** [comment]
@vwilliamsn thanks!  i will fix errors and then rerun.

**Review by vwilliamsn — APPROVED** [review]
Great job @c2nelson!

**Pull request merged**
