### PR TITLE
Moving modal and redirect modal out from Jekyll build pipeline into Webpack

### PR DESCRIPTION
**Pull request by JackRyan1989**
modal.js and redirect-modal.js are now named functions that are called in each file. They are now built by webpack. They function identically to before the migration to Webpack. 

To test:
1. Open the preview url below
2. Open a link to an external page (you can try the Adobe Stock image link in the homepage footer)
3. Confirm that the modal works as on the existing beta.ada.gov site

### CODE REVIEW

**Comment by JackRyan1989** [comment]
@eileen-nava Thank you! I have escalated the issue with Federalist as there appears to be an issue with the S3 bucket.

**Comment by eileen-nava** [comment]
@JackRyan1989 Got it!  Please ping me again once you need a review.

**Comment by JackRyan1989** [comment]
@eileen-nava can you review?

**Review by eileen-nava — APPROVED** [review]
Looks good, @JackRyan1989!

**Review by billyhunt — APPROVED** [review]
Looks good to me!

**Pull request merged**
