### PR TITLE
Homepage redesign

### PR DESCRIPTION
**Pull request by JackRyan1989**
We are redesigning the homepage to meet better highlight information users have found most helpful

### CODE REVIEW

**Comment by beckyslogeris** [comment]
@JackRyan1989 

1. Overall design looks great! 
2. The hover states work for What's on ADA.gov. Wondering if we should also add links to the titles - "Featured Topics", etc. that link to those pages? What do you think?
3. Can you send me the dimensions you need for the hero image?

**Comment by JackRyan1989** [comment]
@beckyslogeris The headings could be links, but it would feel a bit redundant since we have the nav at the top. I don't know that those links would add much value for users.

The image size we need is 2203 x 1100 px.

**Comment by beckyslogeris** [comment]
Here you go! Let me know if this works.
ADAheroimage2203x1100

**Comment by JackRyan1989** [comment]
@beckyslogeris Thanks! So, I think the image needs to be redone yet again. Even at 2400 px wide we get overlap between the image and the text. See attached screenshot. I guess make the image significantly wider, maybe by like another 400px?

Screen Shot 2022-10-07 at 2 00 34 PM

**Comment by beckyslogeris** [comment]
Here's are two options!
ADAheroimage2603x1100

ADAheroimage2803x1100

**Comment by beckyslogeris** [comment]
@JackRyan1989 - sorry for the delay on this! Still digging myself out of emails... What are the specs for the tablet size image? Let me know and I can work on something.

**Comment by JackRyan1989** [comment]
@beckyslogeris No worries! So tablet width is 640px - 1023px. 

The version of the image I used in the latest screen shots there is 2803x1100

**Comment by beckyslogeris** [comment]
@JackRyan1989 - just tried playing around with the image and it ends up looking funky with the narrower width. Could we use the full image instead like we have for the mobile version? 

Screen Shot 2022-11-03 at 3 58 27 PM

**Comment by JackRyan1989** [comment]
@beckyslogeris So you're saying we should have the hero image section look identical on mobile and tablet screens, correct? I can certainly try that.

**Comment by beckyslogeris** [comment]
@JackRyan1989 - yep! I think that will be better.

**Comment by JackRyan1989** [comment]
@vwilliamsn @c2nelson @beckyslogeris Here's how it looks on Tablet (identical to mobile):

Screen Shot 2022-11-04 at 11 14 42 AM


And here's how it looks at 1024 px, which is the smallest desktop width. It's slightly cutoff, how do you feel about that @beckyslogeris @vwilliamsn @c2nelson ?

Screenshot 2022-11-04 at 11-14-11 The Americans with Disabilities Act


And here's how it looks at full width on desktop:

Screenshot 2022-11-04 at 11-16-39 The Americans with Disabilities Act

**Comment by vwilliamsn** [comment]
@JackRyan1989 and @beckyslogeris is it possible to make the image smaller so everyone can fit? We would like to have everyone represented.  I feel like we shouldn't use that image if we can't see everyone.  We hoped for branding purposes to have the same image across all platforms.

**Comment by JackRyan1989** [comment]
@vwilliamsn @beckyslogeris @c2nelson  Ok, I think this can be the plan moving forward:

1. I remove the new image from this pull request
2. The rest of this pull request can go live once @c2nelson and I have the content in place. 
3. We keep the old image for the time being, and work on finding a new image after launch.

Let me know if anyone has any questions or concerns!

**Comment by beckyslogeris** [comment]
@JackRyan1989 & @vwilliamsn - just updated the image for the smallest desktop width.

ADAheroimage1024

@JackRyan1989 - if we change the line length of the paragraph that should work:

Disability rights are civil rights. From 
voting to parking, the ADA is a law 
that protects people with disabilities 
in many areas of public life.

Let me know!

**Comment by JackRyan1989** [comment]
@beckyslogeris I think that definitely looks better:

Screen Shot 2022-11-07 at 9 54 45 AM

**Comment by beckyslogeris** [comment]
@JackRyan1989 Awesome! Can we pull the text width out just a smidge? So that we don't have "life" on a line by itself at the end...

**Comment by beckyslogeris** [comment]
Yes! Looks great!

**Comment by c2nelson** [comment]
Awesome @JackRyan1989

**Comment by vwilliamsn** [comment]
Looks great @JackRyan1989 and @beckyslogeris!

**Comment by JackRyan1989** [comment]
@beckyslogeris As per @vwilliamsn's statement above, we also need a version of the image for mobile and tablet screens. This version doesn't need any addition white space added to it. But it does need to have the following dimensions: 1086 × 697

Let me know if you have any other questions!

**Comment by JackRyan1989** [comment]
@beckyslogeris Thanks!

@c2nelson @vwilliamsn Image is the same across devices. Let me know what you think:

Screen Shot 2022-11-09 at 2 13 07 PM
Screen Shot 2022-11-09 at 2 13 18 PM
Screen Shot 2022-11-09 at 2 13 34 PM

**Comment by vwilliamsn** [comment]
> @beckyslogeris Thanks!
> 
> @c2nelson @vwilliamsn Image is the same across devices. Let me know what you think:
> 
> Screen Shot 2022-11-09 at 2 13 07 PM
> 
> Screen Shot 2022-11-09 at 2 13 18 PM
> 
> Screen Shot 2022-11-09 at 2 13 34 PM

@JackRyan1989 & @beckyslogeris - great job, the images look great across all devices.

**Review by vwilliamsn — APPROVED** [review]
Thanks @JackRyan1989!

**Review by c2nelson — APPROVED** [review]
@JackRyan1989 @beckyslogeris great job!  i'm excited for this!

**Pull request merged**
