### PR TITLE
Add new best bet box type

### PR DESCRIPTION
**Pull request by kewitham**
Mock of new best bet box with links and no descriptions:
image

### CODE REVIEW

**Review by okkays — APPROVED** [review]
LGTM

**Comment by randyabramson** [comment]
Looks good to me @kewitham. Question - is the top line (Child Care) hyperlinked? If not, maybe we should take away the underline?

**Comment by kewitham** [comment]
> Looks good to me @kewitham. Question - is the top line (Child Care) hyperlinked? If not, maybe we should take away the underline?

It is hyperlinked but we can also set it up to not be hyperlinked and have all the links below it.

**Review by nguyen-tina — COMMENTED** [review]
Removing the larger 'Child Care' hyper link would also remove the link to the Child Care topics page. For that reason, I'm inclined to keep it! 

Visual question: Why is that text larger than the usual best bet link text size? Is it because it's a collection of links? Just want to clarify any new pattern that may be emerging here.

**Comment by kewitham** [comment]
> 

@nguyen-tina we can keep the Child Care as just a plaintext title and add the child care topics page underneath if we want. The text for the links below the title link are the same size as the other best bet links but we have full control over the size so if you have a recommendation I can implement it.

**Comment by nguyen-tina** [comment]
Got it – In that case, I would keep Child Care as a title (without the underline), and add the Child Care topics page as the first link of the set. Perhaps the title of that topics page could be, 'Child Care: Topic overview'

cc @vwilliamsn

**Comment by vwilliamsn** [comment]
> Got it – In that case, I would keep Child Care as a title (without the underline), and add the Child Care topics page as the first link of the set. Perhaps the title of that topics page could be, 'Child Care: Topic overview'
> 
> cc @vwilliamsn

I like @nguyen-tina recommendations. Let's go with that.

**Comment by kewitham** [comment]
> > Got it – In that case, I would keep Child Care as a title (without the underline), and add the Child Care topics page as the first link of the set. Perhaps the title of that topics page could be, 'Child Care: Topic overview'
> > cc @vwilliamsn
> 
> I like @nguyen-tina recommendations. Let's go with that.

updated!

**Review by vwilliamsn — APPROVED** [review]
Looks good thanks @kewitham!

**Comment by kewitham** [comment]
> Looks good thanks @kewitham!

@vwilliamsn do we want to match the service animals best bet box to this one or keep it as is? Here is what it looks like now:
image
We probably should pick a consistent design across all best bet boxes.

**Comment by vwilliamsn** [comment]
> > Looks good thanks @kewitham!
> 
> @vwilliamsn do we want to match the service animals best bet box to this one or keep it as is? Here is what it looks like now: image We probably should pick a consistent design across all best bet boxes.

Good point @kewitham!  I agree we need to have a consistent look and feel for the best bet boxes. With that in mind let's have the service animals best bet box format be our standard format for all of the best bet boxes.

**Comment by kewitham** [comment]
@vwilliamsn sounds good! I forgot to note that the text best bet (the version we are using for service animals) only allows you to recommend two results whereas this graphic best bet version allows you to recommend as many results are you want. Wanted to flag in case that changes things.

**Comment by vwilliamsn** [comment]
@kewitham thanks for pointing that out. I think providing the users with access to more content related to their search term, would be best.  So, I'm (now) inclined to go with the graphic option. Sorry for flip flopping on this. That also means the service animal best bet box would need to change and we can add a third option: [Frequently Asked Questions about Service Animals and the ADA](https://www.ada.gov/resources/service-animals-faqs/ ). Yay!  Happy to chat about this tomorrow at stand-up if you have any questions.

**Comment by kewitham** [comment]
> @kewitham thanks for pointing that out. I think providing the users with access to more content related to their search term, would be best. So, I'm (now) inclined to go with the graphic option. Sorry for flip flopping on this. That also means the service animal best bet box would need to change and we can add a third option: [Frequently Asked Questions about Service Animals and the ADA](https://www.ada.gov/resources/service-animals-faqs/). Yay! Happy to chat about this tomorrow at stand-up if you have any questions.

sounds good! updated!

**Pull request merged**
