### PR TITLE
Enforcement Page Redesign

### PR DESCRIPTION
**Pull request by okkays**
Do not merge until subsequent PRs are approved and merged!

- 🌎 We're re-formatting the enforcement page
- ⛔ There are a variety of modules with differently formatted content
- ✅ This commit adds the basic content without formatting future commits
- 🔮 Future commits will format this content

image

### CODE REVIEW

**Review by Rwolfe-Nava — APPROVED** [review]

**Comment by vwilliamsn** [comment]
@okkays - this should be the last round of edits from leadership.

1. Under Featured Topics - change term from Integration/Olmstead -> Community Integration
2. Under Most Viewed Cases - remove Utah Department of Corrections case
3. Make Press Release plural -> Press Releases
4. Under Additional Topics - remove New Construction
5. Under Additional Topics - change Program Access -> Physical Access. 
We have a technical issue with the link for “Physical Access” that Darren’s looking into. So, I don’t have an updated link yet.

**Review by vwilliamsn — CHANGES_REQUESTED** [review]
@okkays - https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/912#issuecomment-2528120779

cc: @Rwolfe-Nava @c2nelson

**Review by vwilliamsn — APPROVED** [review]
LGTM! Thanks @okkays!!!

**Comment by c2nelson** [comment]
@okkays @vwilliamsn - Let's add the Enforcement to the News Widget also

**Pull request merged**
