### PR TITLE
Add submenu items to law and regs top nav

### PR DESCRIPTION
**Pull request by kewitham**
**Before**
Screenshot 2024-01-08 at 10 02 25 AM

**After**
Screenshot 2024-01-08 at 10 03 38 AM

### CODE REVIEW

**Comment by c2nelson** [comment]
@kewitham I like.  Thank you!  @vwilliamsn I'm wondering if it should say "the ADA" Thoughts?

**Review by okkays — APPROVED** [review]
Nice! LGTM on mobile/desktop/sr

Approval pending wording tweaks from @c2nelson's comment

**Comment by sanchez-amanda** [comment]
Just one thing! Can we add the same amount of padding we have the right side to the left side? the padding on the left is a little too close to the container. other than that, looks great!!! @kewitham

**Comment by vwilliamsn** [comment]
I love this @kewitham - great job! 

@kewitham @sanchez-amanda - I wonder if there's a way to let folks know that the Law & Regs is a 'homepage or landing page', not sure which is the proper way to refer to it. Maybe there's some other term we can use but I don't think it's obvious to users that if they are unsure of what document they need, clicking on the Law & Regs (in the hamburger feature) could provide some guidance.

**Comment by vwilliamsn** [comment]
> @kewitham I like. Thank you! @vwilliamsn I'm wondering if it should say "the ADA" Thoughts?

@kewitham I agree with @c2nelson - we can say "the ADA" or spell out Americans with Disabilities Act

**Comment by vwilliamsn** [comment]
@kewitham - would you please add the federalist preview link to this ticket. Thanks!

**Comment by kewitham** [comment]
> @kewitham - would you please add the federalist preview link to this ticket. Thanks!

here it is! [federalist link](https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.sites.pages.cloud.gov/preview/usdoj-crt/beta-ada/kw/933/update-law-reg-nav/)

**Review by vwilliamsn — APPROVED** [review]
LGTM, thanks @kewitham!

**Review by c2nelson — CHANGES_REQUESTED** [review]
@vwilliamsn @kewitham  - FWIW I still think we should have "The" in front of Americans with Disabilities Act.   And it should be indented and unbolded.  Also on the Regulations landing page I see closing div tags </div>.

**Comment by vwilliamsn** [comment]
> @vwilliamsn @kewitham - FWIW I still think we should have "The" in front of Americans with Disabilities Act. And it should be indented and unbolded. Also on the Regulations landing page I see closing div tags . Great job, everyone. It is awesome.

@c2nelson thanks for weighing in on this, it looks like Katie did both, it's "The ADA" on mobile and "Americans with Disabilities Act" on desktop. @kewitham, I think Cindy flagged that the “Americans with Disabilities Act”/”The ADA” should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented.

**Comment by kewitham** [comment]
> > @vwilliamsn @kewitham - FWIW I still think we should have "The" in front of Americans with Disabilities Act. And it should be indented and unbolded. Also on the Regulations landing page I see closing div tags . Great job, everyone. It is awesome.
> 
> @c2nelson thanks for weighing in on this, it looks like Katie did both, it's "The ADA" on mobile and "Americans with Disabilities Act" on desktop. @kewitham, I think Cindy flagged that the “Americans with Disabilities Act”/”The ADA” should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented.

@vwilliamsn @c2nelson  So should I have it as "The Americans with Disabilities Act" and "The ADA"?

**Comment by vwilliamsn** [comment]
> > > @vwilliamsn @kewitham - FWIW I still think we should have "The" in front of Americans with Disabilities Act. And it should be indented and unbolded. Also on the Regulations landing page I see closing div tags . Great job, everyone. It is awesome.
> > 
> > 
> > @c2nelson thanks for weighing in on this, it looks like Katie did both, it's "The ADA" on mobile and "Americans with Disabilities Act" on desktop. @kewitham, I think Cindy flagged that the “Americans with Disabilities Act”/”The ADA” should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented.
> 
> @vwilliamsn @c2nelson So should I have it as "The Americans with Disabilities Act" and "The ADA"?

@kewitham sorry for the confusion. It should be "The Americans with Disabilities Act" on desktop and "The ADA" on mobile.

**Comment by vwilliamsn** [comment]
@kewitham - just checking in on this 1 change request (see below) to the submenu, has it been made?

In the submenu 'Americans with Disabilities Act' (desktop) & 'The ADA' (mobile) should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented. 

cc: @c2nelson @sanchez-amanda

**Comment by kewitham** [comment]
> @kewitham - just checking in on this 1 change request (see below) to the submenu, has it been made?
> 
> In the submenu 'Americans with Disabilities Act' (desktop) & 'The ADA' (mobile) should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented.
> 
> cc: @c2nelson @sanchez-amanda

@vwilliamsn not yet, I wasn't prioritizing updates to this since we're still waiting for approval on the law and regs redesign changes it's dependent on but I can move it up the priority list if needed!

**Comment by vwilliamsn** [comment]
> > @kewitham - just checking in on this 1 change request (see below) to the submenu, has it been made?
> > In the submenu 'Americans with Disabilities Act' (desktop) & 'The ADA' (mobile) should be indented and unbolded like the other direct access pages. Only the three landing pages should be bolded and not indented.
> > cc: @c2nelson @sanchez-amanda
> 
> @vwilliamsn not yet, I wasn't prioritizing updates to this since we're still waiting for approval on the law and regs redesign changes it's dependent on but I can move it up the priority list if needed!

@kewitham No worries, you can finish what you're working on. We can make these changes next Sprint. I have some updates from leadership (for the law, regs, & standards), but we are still waiting for final approval.

**Comment by kewitham** [comment]
@vwilliamsn These changes are now here: https://github.com/usdoj-crt/beta-ada/pull/748 including the latest request to unbold and indent The ADA.
Closing this PR out

**Pull request closed without merging**
