### PR TITLE
Voting overlay

### PR DESCRIPTION
**Pull request by c2nelson**
voting overlay draft.  image still needs procuring for topics card.

### CODE REVIEW

**Comment by vwilliamsn** [comment]
@c2nelson this looks great - one small change:

**under Other Federal Laws That Protect the Rights of Voters with Disabilities**
- bullets needed (see below) in the Help America Vote Act of 2002 description

Requires election officials responsible for conducting federal elections to: 
* provide at least one accessible voting system for persons with disabilities at each polling place; and 
* ensure that the accessible voting system provides the same privacy and independence that other voters receive.

**Comment by vwilliamsn** [comment]
@c2nelson - other then adding the image, has the above edits been made?

**Comment by c2nelson** [comment]
@vwilliamsn image added.  ready to go.

**Review by vwilliamsn — APPROVED** [review]
You rock - thanks for your work on this @c2nelson !

**Pull request merged**
