### PR TITLE
Update ruby to version 2.7.0

### PR DESCRIPTION
**Pull request by JackRyan1989**
Rationale: Via Cloud.gov --  If you have a Federalist site using Jekyll and you specify your version of Ruby to 2.6, you will need to update your site to use version 2.7 or higher as soon as possible.  Ruby 2.6 is end of life and has been deprecated which means it will no longer receive any fixes. Due to this, **Federalist no longer supports Ruby version 2.6 and your site will not build or update if you continue to use it.**

**Changes:** 

1.  Updated the Ruby version to 2.7.0 in the A11y.yml github workflow
2.  Updated Ruby version to 2.7.0 in the Linter github workflow
3.  Updated the Ruby version in the Gemfile and created new Gemlock file.

### CODE REVIEW

**Comment by billyhunt** [comment]
@JackRyan1989  can you add steps to update to Ruby locally to the documentation?

**Comment by JackRyan1989** [comment]
@billyhunt yes absolutely. Would you like me to make that part of this PR?

**Comment by JackRyan1989** [comment]
@billyhunt I've added a quick write up here: https://github.com/usdoj-crt/beta-ada/wiki/Managing-Ruby-Versions

**Review by billyhunt — APPROVED** [review]
Looks good to me!

**Pull request merged**
