### PR TITLE
Related content component

### PR DESCRIPTION
**Pull request by JackRyan1989**
Rationale:
1. User research has shown that users want multiple entry points for each page. The related content component allows users to see multiple pages thematically related to the one they are currently on.

Changes:
1. A new component has been created in the `_includes/` folder called `related-content.html`
2. This component is based off of the USWDS [Summary Box component](https://designsystem.digital.gov/components/summary-box/)
3. To use it, it needs to be declared in the frontmatter of the page it will be one using `related-content: true`
4. Tags need to be specified in an array within the front matter of pages and on the page it will be used on. `tags: [tag1, tag2, tag3]`
5. Tags also need to be whitelisted in a .yml file in the `_data/` directory. The file `tags.yml` contains a list of allowed tags that needs to contain the tags you have in your page's frontmatter. 

Tests:
1. @chinelo-ikejimba We need to see what this will look like on mobile. 
2. Check on multiple browsers
3. Check on mobile devices
4. Try adding news tags without adding to the white list
5. Make sure all pages with appropriate tags are listed

### CODE REVIEW

**Comment by JackRyan1989** [comment]
@chinelo-ikejimba @c2nelson  to view the related content item, go to the web guidance page.

**Review by chinelo-ikejimba — COMMENTED** [review]
@JackRyan1989 please refer to [ticket 422](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/422) for design handoff showing mobile and tablet designs

I'll walkthrough some design changes to check for impact this morning

**Comment by JackRyan1989** [comment]
Just checked across browsers. All looked good across Safari, Edge, Firefox, and Chrome. Looked good on Samsung Android device and iPhone. 

Screen reader test on Chrome (mac os), and Firefox and Edge on Windows seem good. 

1 small change is needed. The links in the related content box need hover/focus styling to match other links.

Pics from mobile device test:

Screen Shot 2022-04-06 at 3 00 24 PM
Screen Shot 2022-04-06 at 3 00 34 PM

**Comment by chinelo-ikejimba** [comment]
Related Content summary box moved to bottom of main content as seen in [Layout for Design Standards](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/432#issuecomment-1104051650)

**Review by chinelo-ikejimba — APPROVED** [review]
Looks good @JackRyan1989!

**Pull request merged**
