### PR TITLE
Homepage alert site redesign

### PR DESCRIPTION
**Pull request by JackRyan1989**
@nguyen-tina Please use the preview link to review the styling.

Once that is approved we can merge this in and make it live.

### CODE REVIEW

**Comment by nguyen-tina** [comment]
@JackRyan1989 

The link looks great, but there alert looks a bit odd with the blue sides -- is there any way we can make the yellow be the same color throughout the length of the alert? Can keep the bold yellow line where it's at

**Comment by JackRyan1989** [comment]
@nguyen-tina I think I've addressed you concerns. Let me know if you see anything else.

**Review by vwilliamsn — APPROVED** [review]
This looks great - thanks @nguyen-tina and @JackRyan1989!

**Comment by nguyen-tina** [comment]
Thanks for making the changes, Jack! I took one more look, and think the darker yellow "alert bar" is actually distracting and doesn't add much for the full-page width alert. Can you remove it? I believe the design is still noticeable and effective without it.

Other examples of sites using the alert banner without the vertical alert bar: [va.gov](https://www.va.gov/?next=%2Fmy-va%2F) and [vote.gov](https://vote.gov/)

**Comment by JackRyan1989** [comment]
> Thanks for making the changes, Jack! I took one more look, and think the darker yellow "alert bar" is actually distracting and doesn't add much for the full-page width alert. Can you remove it? I believe the design is still noticeable and effective without it.
> 
> Other examples of sites using the alert banner without the vertical alert bar: [va.gov](https://www.va.gov/?next=%2Fmy-va%2F) and [vote.gov](https://vote.gov/)

Border removed @nguyen-tina !

**Comment by vwilliamsn** [comment]
@JackRyan1989 - please provide an updated federalist link.

**Comment by JackRyan1989** [comment]
@vwilliamsn https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/jr/homepage-alert-redesign-632/

**Review by nguyen-tina — APPROVED** [review]
Looks great to me!

**Pull request merged**
