### PR TITLE
Topics page enhancements

### PR DESCRIPTION
**Pull request by kewitham**
[Issue #821](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/821)

This PR implements the topic page redesign linked in the above issue.
image

Note: holding off on merging this until we have new hero image
Note: mobile carousel will be handled in another PR

### CODE REVIEW

**Comment by vwilliamsn** [comment]
@kewitham - LGTM! Would you please add the federalist link to this card?

**Review by okkays — APPROVED** [review]
Code LGTM - thanks for taking care of the image optimizations, that's a nice bonus!

I'm going to approve but add the "do not merge" label pending the hero image.

**Comment by vwilliamsn** [comment]
7/27 update - @kewitham we should have an image for you hopefully tomorrow. @c2nelson found an image, we're awaiting approve to use that image.

**Review by vwilliamsn — APPROVED** [review]
LGTM!

**Pull request merged**
