### PR TITLE
Opdmds ta

### PR DESCRIPTION
**Pull request by c2nelson**

### CODE REVIEW

**Comment by JackRyan1989** [comment]
@c2nelson I see that you have the figures placed in tables here. We'll need design review by @chinelo-ikejimba or @beckyslogeris to make sure that is ok, because it is different than the design I had been working on for the Design Standards. Also, I noticed there is a bunch of text at the bottom of the page, and I wonder if we need it as it is captured elsewhere on the page?

Screen Shot 2022-08-23 at 3 20 34 PM

**Comment by vwilliamsn** [comment]
@JackRyan1989 - REF: the text at the bottom of the page

We encourage printing/duplication for all of our publications, so although it's not needed when viewed on the web, it's extremely helpful as a printed document so users know how to contact us.

**Comment by vwilliamsn** [comment]
@c2nelson @JackRyan1989 @beckyslogeris @chinelo-ikejimba

Please let me know when it's okay to approve this pull request.

**Comment by JackRyan1989** [comment]
@vwilliamsn Ok yes that does make sense. I was wondering more about the first line telling users to go to ADA.gov for more information, do you think we need that?

**Comment by c2nelson** [comment]
thanks, @JackRyan1989  I added the caption element to the images.  Captions are not necessary for this piece so I am going to remove them so to avoid delay and added discussion.

**Comment by vwilliamsn** [comment]
@JackRyan1989 is there a way to have information show-up on the printed document, that's not viewable on the web version?

If not, we need to keep that language as when the document is printed and handed to a business owner for example, they would need to know that they can go to ADA.gov for more information or call the ADA Info line if they have questions.

**Comment by chinelo-ikejimba** [comment]
@c2nelson @JackRyan1989 @beckyslogeris @vwilliamsn 

**Suggested design notes**
Let's follow the figure and image working format @JackRyan1989 has for the 1991 Design Standards with the following guidelines:
- no border around figures/images
- caption placed in body text beneath the figure/image

**Comment by JackRyan1989** [comment]
> @JackRyan1989 is there a way to have information show-up on the printed document, that's not viewable on the web version?
> 
> If not, we need to keep that language as when the document is printed and handed to a business owner for example, they would need to know that they can go to ADA.gov for more information or call the ADA Info line if they have questions.

Yes! I don't have that style rule written yet. But that is something I can do when I get back. Is that something you would like applied anywhere this kind of text exists @vwilliamsn?

**Comment by vwilliamsn** [comment]
Great - thanks for that information @JackRyan1989. Let's chat more when you get back.

**Review by vwilliamsn — CHANGES_REQUESTED** [review]
This looks great thanks for your work on this @c2nelson!  One small change request - one of the images looks off, it doesn't align with the text on the page.

**Comment by c2nelson** [comment]
@vwilliamsn indented the image.

**Review by vwilliamsn — APPROVED** [review]
You're the best, thanks for your work on this @c2nelson!

**Pull request merged**
