### PR TITLE
added hyperlinks to ADA infoline page from these pages

### PR DESCRIPTION
**Pull request by c2nelson**

### CODE REVIEW

**Review by JackRyan1989 — CHANGES_REQUESTED** [review]
Lookin' good @c2nelson!

I think you need to make sure the second mention of the ADA Information Line in the file-a-complaint.md page is also a link to be consistent. Finally, please add the link to the presente-una-queja.md page any time the phrase "línea informativa de la ADA" appears.

**Comment by JackRyan1989** [comment]
Looks good @c2nelson ! Can you merge in the latest changes you pushed to main and make sure that the links are present in that TA as well?

Thanks!

**Review by JackRyan1989 — CHANGES_REQUESTED** [review]
Merge in main and make sure the links are present on the Restriping TA page.

**Comment by c2nelson** [comment]
@JackRyan1989 Voila!

**Review by JackRyan1989 — APPROVED** [review]
Looks good @c2nelson

**Review by vwilliamsn — APPROVED** [review]
Thanks @c2nelson - great job!

**Review by chinelo-ikejimba — APPROVED** [review]
Well done!

**Pull request merged**
