### PR TITLE
Law and Regs redesign

### PR DESCRIPTION
**Pull request by kewitham**
This PR contains all the changes for the law and reg page redesign and the top nav updates - recreated to address git conflicts.

Image

Image

Image

Image

### CODE REVIEW

**Review by okkays — APPROVED** [review]
nice work @kewitham! code lgtm!

**Comment by randyabramson** [comment]
Really nice work, gang! (just one note: the breadcrumb for the laws and regs home page link is broken)

**Comment by kewitham** [comment]
> Great job @kewitham!
> 
> A couple of changes are needed: • 1) add back in the Law, Regs & Standards landing page to the submenu in the top navigation, I think with all the conversations around how to display the “law”, The ADA (on mobile) & The Americans with Disabilities Act (on desktop) it fell off as an item in the submenu, • 2) note that ‘Law, Regs & Standards’ should be bolded and not indented (as it’s a landing page), • 3) under Regulations it should read Title II Regulation and Title III Regulation, and • 4) update the language to say Guidance to the 2010 Standards
> 
> Also, I can't access the 'Law, Regs & Standards' landing page because it's not in the top navigation menu or the left side navigation. Looking at the screen shots above, it looks like we can remove 'Law, Regulations & Standards Documents'. Since that's similar to the name of the page, I don't think we need it twice.
> 
> Everything else looks good. Happy to chat if you have any questions. cc: @sanchez-amanda

@vwilliamsn @sanchez-amanda 
1. Good catch!
2. Noted
3. Want to flag that the title of those pages has regulations in its plural form: 
image
4. Got it

For the last note, I think the idea with the 'Law, Regulations & Standards Documents' heading was to split up the page and to distinguish that section from the following sections (Resources and Proposed Changes). cc: @sanchez-amanda

**Comment by kewitham** [comment]
> Really nice work, gang! (just one note: the breadcrumb for the laws and regs home page link is broken)

@randyabramson that's a bug with the federalist preview - not all internal links work - but it works on the local version

**Comment by sanchez-amanda** [comment]
I can see how they think it might be redundant - i wonder if we can just keep it to 'Documents'? Or something else? It would flow a little weirdly without it. I can't think of anything else to call it though. But if this is something leadership wants, i'm okay with it. We should track touchpoints feedback to see if not explicitly calling out 'documents' is jarring to what users might expect when they click on it.

For the other headings in regards to adding them to the side nav - I would hold off on adding Resources + Proposed Changes into the side nav (keep as is). The page isn't super long and the assumption here is that people are looking for quick access to the documents, not the other parts (proposed changes + resources) - for example, the resources are really there for the folks that take time with the page (the non-experts). We can keep the most important/used links highlighted in the nav for now. @kewitham @vwilliamsn

**Comment by vwilliamsn** [comment]
@sanchez-amanda & @kewitham - let me circle back to leadership to see if there is any flexibility in keeping 'Law, Regulations & Standards Documents'

**Comment by vwilliamsn** [comment]
> @sanchez-amanda & @kewitham - let me circle back to leadership to see if there is any flexibility in keeping 'Law, Regulations & Standards Documents'

@kewitham & @sanchez-amanda - quick update, leadership wants us to move forward with removing the ‘redundant’ language. I know that it’s not ideal. I will continue to work on this issue. In the meantime, let’s move forward with making the appropriate changes so we can merge the pending updates. If we get feedback from users that the page isn't working for them, I'm happy to take that information back to leadership (with a request to add the proposed language).

Happy to chat if you have any questions.

**Comment by kewitham** [comment]
> > @sanchez-amanda & @kewitham - let me circle back to leadership to see if there is any flexibility in keeping 'Law, Regulations & Standards Documents'
> 
> @kewitham & @sanchez-amanda - quick update, leadership wants us to move forward with removing the ‘redundant’ language. I know that it’s not ideal. I will continue to work on this issue. In the meantime, let’s move forward with making the appropriate changes so we can merge the pending updates. If we get feedback from users that the page isn't working for them, I'm happy to take that information back to leadership (with a request to add the proposed language).
> 
> Happy to chat if you have any questions.

@vwilliamsn made all approved updates!

**Review by vwilliamsn — CHANGES_REQUESTED** [review]
@kewitham - great job!!! Everything looks really good. I have one question and one request.
 1) Question - about the legal documents "in-line tools", they don't show up in the documents when using the Federalist link, is that just a bug?
2) Request - Apologies, there are a couple of places that just say Regulation "singular" instead of Regulations "plural". That's on me, I asked Amanda to make those changes to the mocks she gave you. I flagged that incorrectly, would you mind changing those as well? I pulled screenshots of when/where the changes are needed. Thank you!

image
image
image

**Comment by kewitham** [comment]
@vwilliamsn made those updates! For the law and regs tools, I think it's just an issue with federalist because they are showing up locally

**Review by vwilliamsn — APPROVED** [review]
LGTM, thanks @kewitham!

**Pull request merged**
