### PR TITLE
Title2&3 primers

### PR DESCRIPTION
**Pull request by c2nelson**

### CODE REVIEW

**Comment by JackRyan1989** [comment]
@c2nelson Is all of the text in the "overview of accessible parking requirements" available in the document? If not, we might want to put it in the alt text or figcaption.

**Review by vwilliamsn — CHANGES_REQUESTED** [review]
Thanks for your work on this @c2nelson - it's looking good, a few minor changes are needed. This is approved once the changes have been made. Thanks!

**Under New Customers:**
- add hyperlink to New Construction and Alterations

**Under Existing Facilities - Element by Element Safe Harbor**
- Separate the paragraphs 

The 2010 Standards lower the mounting height for light switches and thermostats from 54 inches to 48 inches. If your light switches are already installed at 54 inches in compliance with the 1991 Standards, you are not required to lower them to 48 inches.

The 1991 Standards require one van accessible space for every eight accessible spaces. The 2010 Standards require one van accessible space for every six accessible spaces. If you have complied with the 1991 Standards, you are not required to add additional van accessible spaces to meet the 2010 Standards.

The 2010 Standards contain new requirements for the input, numeric, and function keys (e.g. "enter," "clear," and "correct") on automatic teller machine (ATM) keypads. If an existing ATM complies with the 1991 Standards, no further modifications are required to the keypad.

**Under Barrier Removal Before March 15, 2012**
- add hyperlink and italic
(See, _ADA 2010 Revised Requirements: Effective Date / Compliance Date_ at [www.ada.gov/ revisedeffectivedates-2010.htm](https://www.ada.gov/regs2010/revised_effective_dates-2010.htm)) 

**Lastly**, at the bottom of the document the date (March 16, 2011) appears twice - do we need to have it represented two time?

**Comment by c2nelson** [comment]
@vwilliamsn changes made.

**Comment by vwilliamsn** [comment]
Again thanks for your work on the Primers @c2nelson! T2 Primer - I have a few questions about the styling of this document and a few minor changes are need.

Edits first:
**Intro paragraphs** 
- check the size or font style paragraph 3 looks different then the first 2
- remove space before the last 'period' in the last paragraph

**Under ADA Coordinator, Grievance Procedure, Self-Evaluations, and Transition Plans**
- add hyperlink to [ADA Best Practices Tool Kit for State and Local Governments](https://www.ada.gov/regs2010/titleII_2010/pcatoolkit/chap2toolkit.htm). 

**Under ADA Information Resources**
- add U.S. Department of Justice a line above "For more info... (see below)

U.S. Department of Justice

For more information about the revised ADA regulations and the 2010 Standards, please visit the Department of Justice's website or call our toll-free number."

The [ADA Requirement: Service Animals](https://beta.ada.gov/resources/service-animals-2010-requirements/) - add print button

**These are style questions - happy to discuss if you have questions.**

1. T2 Primer is visually text heavy - even with the bullets the text runs together.  Have we considered adding a space between each bullet, to help with readability? @c2nelson @JackRyan1989 @beckyslogeris - what do you think?

2. When comparing the T2 Primer on legacy w/ this version, I can see that we don't have any of the docs we link to in PDF (which is available on the legacy site).  
- will we need to add PDF's now (time permitting) or just update this document/page when we add PDF's at a later date?

**Comment by vwilliamsn** [comment]
Thanks for making the changes to the T3 Primer @c2nelson - can you send a new Federalist link so I can see the changes. Thanks!

**Comment by c2nelson** [comment]
On 9/9 @vwilliamsn and i discussed questions above.

**Review by vwilliamsn — APPROVED** [review]

**Review by vwilliamsn — APPROVED** [review]

**Pull request merged**
