### PR TITLE
servicemembers TA

### PR DESCRIPTION
**Pull request by c2nelson**

### CODE REVIEW

**Comment by c2nelson** [comment]
@vwilliamsn Let's discuss this one.  There are quite a few one-offs that need addressing.

**Comment by vwilliamsn** [comment]
@c2nelson you did a great job on this document! I only saw one change that's needed. In the title of the document, you can remove the second 'Know Your Rights'. 

Also, I see the note in this ticket, let's chat and make decisions about the one-offs at tomorrow 1:1.

**Comment by vwilliamsn** [comment]
@c2nelson looks great 1 small fix - just need to make this a hyperlink
image

**Review by vwilliamsn — APPROVED** [review]
LGTM, thanks @c2nelson!

**Pull request merged**
