### PR TITLE
Content type icons: Update the Related Content boxes to include icons

### PR DESCRIPTION
**Pull request by okkays**
Shows icons and category name for related pages.

- 🌎 The related content box shows what other information is similar to the current page.
- ⛔ Right now it's hard to know whether that information is more/less technical
- ✅ This commit adds page type indicators to help illuminate.

(Let me know if we want shorter text titles for these - I saw in the mock that "Guidance" was shorter, but wasn't sure what to use to shorten laws/regs/standards)

### Desktop:

image

image

### Mobile:

image

image

### CODE REVIEW

**Comment by okkays** [comment]
Also, probably worth noting that I've confirmed the only related content we have right now falls into one of the categories of Topic, Resource, or Law/Reg.

That is, we don't currently have a need for any sort of "other" page type.

Technical confirmation (confirming that the only pages with "tags", and therefore the only pages that will be listed as repeated content, or in these three collections):

```
└─ $ ws ag "^tags:" -lr
_pages/law-and-regs/index.md
_pages/law-and-regs/design-standards/index.md
_pages/law-and-regs/title-iii-regulations.md
_pages/law-and-regs/title-ii-2010-regulations.md
_pages/_topics/title-iii.md
_pages/_topics/title-ii.md
_pages/_topics/telehealth.md
_pages/_topics/service-animals.md
_pages/_topics/parking.md
_pages/_topics/mobility-devices.md
_pages/_topics/effective-communication.md
_pages/_topics/child-care-centers.md
_pages/_topics/community-integration.md
_pages/_topics/opioid-use-disorder.md
_pages/_resources/web-guidance.md
_pages/_topics/emergency-planning.md
_pages/_resources/service-animals-2010-requirements.md
_pages/_resources/restriping-parking-spaces.md
_pages/_resources/ticket-sales.md
_pages/_resources/service-animal-faqs.md
_pages/_resources/opdmds.md
_pages/_resources/title-iii-primer.md
_pages/_resources/title-ii-primer.md
_pages/_resources/law-enforcement-guide.md
_pages/_resources/medical-care-mobility.md
_pages/_resources/effective-communication.md
_pages/_resources/accessible-pools-requirements.md
_pages/_resources/disability-rights-guide.md
_pages/_resources/child-care-centers.md
_pages/_resources/ai-guidance.md
_pages/_resources/2021-08-25-covid-qa.md
```

**Review by kewitham — APPROVED** [review]
lgtm!

**Comment by nguyen-tina** [comment]
can I get a Federalist link? 🥺

**Comment by nguyen-tina** [comment]
What I'm wondering about right now is: It looks like there isn't 24px of space in between each "content section" (whether vertically or horizontally!). That's the biggest fix I see so far :)

**Comment by okkays** [comment]
@nguyen-tina Weird that the federalist comment didn't post - here's how to access the federalist link if there's no comment

federalist

https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.sites.pages.cloud.gov/preview/usdoj-crt/beta-ada/kk/675/related-type-icons/

**Comment by nguyen-tina** [comment]
That is SUPER helpful, thank you for that tutorial!

**Comment by okkays** [comment]
Added the margin, and merged with changes from the other PR

Here's an extreme example from /law-and-regs/title-ii-2010-regulations/

image

image

**Review by vwilliamsn — APPROVED** [review]
Looks good! Thanks to everyone for their work on this.

**Review by nguyen-tina — APPROVED** [review]
whoops, looks like I missed this review – apologies.

Veronica approved some text changes in ticket 675 – wondering if we can get them in this ticket. Happy to open a new ticket as well, since it has some implications for the navigation.  The changes are:
- "Guidance & Resources" becomes "Guidance"
- "Laws, Regulations, & Standards" becomes "Laws & Regulations"

I'm going to go ahead and approve this PR though, since everything requested for this ticket is complete.

**Pull request merged**
