### PR TITLE
ta - guide to disability rights

### PR DESCRIPTION
**Pull request by c2nelson**

### CODE REVIEW

**Comment by JackRyan1989** [comment]
@c2nelson A11y issues and display issues are fixed. We need to add tags to this page.

**Comment by JackRyan1989** [comment]
@c2nelson I also merged in the main branch.

**Review by JackRyan1989 — CHANGES_REQUESTED** [review]
Please add tags if needed.

**Comment by vwilliamsn** [comment]
Thanks @c2nelson and @JackRyan1989 for your work on this document.  This document links users to other Federal agencies that do disability rights work.  From the current list of tags we can use: #title II, #title III, #employment.

**Comment by JackRyan1989** [comment]
Added tags @vwilliamsn . Approving @c2nelson

**Review by JackRyan1989 — APPROVED** [review]
Approved!

**Pull request merged**
