### PR TITLE
Update text of beta banner

### PR DESCRIPTION
**Pull request by hursey013**
Re: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/239

Updated as per mockups on https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/238#issuecomment-879291207

### CODE REVIEW

**Comment by kstitch7** [comment]
Please add a comma before "and". Looks good.

**Review by kmori — CHANGES_REQUESTED** [review]
Looks good to me as well with the addition @kstitch7 mentioned for comma before " and". Thanks!

**Comment by hursey013** [comment]
@kstitch7 @kmori updated!

**Comment by hursey013** [comment]
Closing as per @kmori's comment here: https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/239#issuecomment-885078942

**Pull request closed without merging**
