### PR TITLE
Rearrange content types on the homepage.

### PR DESCRIPTION
**Pull request by okkays**
Rearrange content types on the homepage to match https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/641#issuecomment-1428630799

- 🌎 The site offers, in increasing levels of technical language, Featured
  Topics, Resources, and Laws & Regulations.
- ⛔ These are out of order on the homepage as is - that is, resources
  are the "step up" from topics, and laws & regs from that.
- ✅ This PR reorganizes them and updates some wording.

image

Full demo across desktop/mobile/large screen:

homepage

### CODE REVIEW

**Comment by nguyen-tina** [comment]
Looking good! The only thing I'll add is a mistake I made in the mocks: For the Service Animals section, you can remove "Featured Topic:" in the "Featured Topic: Service Animals" link under the Featured topics.

**Review by c2nelson — APPROVED** [review]
looks good!

**Review by vwilliamsn — APPROVED** [review]
Great work @nguyen-tina and @okkays!

**Review by kewitham — COMMENTED** [review]
It looks like this is stacked on kk/netlify-pages - is that intentional?

**Comment by okkays** [comment]
@kewitham 

I accidentally based off of it 😅

As I've merged kk/netlify-pages, it's now correct

**Pull request merged**
