### PR TITLE
Restriping parking ta

### PR DESCRIPTION
**Pull request by c2nelson**
initial restriping parking ta doc.  #6 on ta top ten list.

### CODE REVIEW

**Review by chinelo-ikejimba — CHANGES_REQUESTED** [review]
@c2nelson this is coming together nicely. I have 2 short notes for changes below:

1. Let's hide the **Related Content** summary box if there aren't items to list inside.
2. (optional suggestion) In the **Resources section**, what if the "ADA Information Line" were a hyperlink to the Info line page? It's a nice added access point but no worries if that would be a considered substantial edit.

**Comment by JackRyan1989** [comment]
> @c2nelson this is coming together nicely. I have 2 short notes for changes below:
> 
> 1. Let's hide the **Related Content** summary box if there aren't items to list inside.
> 2. (optional suggestion) In the **Resources section**, what if the "ADA Information Line" were a hyperlink to the Info line page? It's a nice added access point but no worries if that would be a considered substantial edit.



> @c2nelson this is coming together nicely. I have 2 short notes for changes below:
> 
> 1. Let's hide the **Related Content** summary box if there aren't items to list inside.
> 2. (optional suggestion) In the **Resources section**, what if the "ADA Information Line" were a hyperlink to the Info line page? It's a nice added access point but no worries if that would be a considered substantial edit.

@chinelo-ikejimba @c2nelson Weird, I could've sworn I added some code to hide the Related Content component when there aren't any available articles, but I don't see that code available. So, maybe I dreamt that? IDK. Anyway I'll add it back in as a commit to this branch, so to address @chinelo-ikejimba's other concern you'll need to pull in the latest changes @c2nelson

**Comment by JackRyan1989** [comment]
@chinelo-ikejimba I think the related content component issue is resolved.

@c2nelson can you confirm which pages need which tags?

**Review by chinelo-ikejimba — APPROVED** [review]
Related Content resolved in my view!

And thank you for adding in the ADA Info Line hyperlink. I realized that me asking for that now means making it consistent across all TA 😅 - can y'all update the other TA with the ADA Info line hyperlink? 😇

**Review by JackRyan1989 — APPROVED** [review]

**Review by vwilliamsn — APPROVED** [review]
Great job @c2nelson!

**Comment by c2nelson** [comment]
Merged 7/20

**Pull request merged**
