### PR TITLE
Fix for search pagination links

### PR DESCRIPTION
**Pull request by hursey013**
Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/281

### CODE REVIEW

**Review by kmori — APPROVED** [review]
Looks good! Confirming that the "Next" and "Previous" are no longer on the page when there are no results
image

**Comment by kmori** [comment]
Should we remove the "Previous" and "Next" when there's only one page worth of results?

**Comment by hursey013** [comment]
> Should we remove the "Previous" and "Next" when there's only one page worth of results?

@kmori We could, although I believe with just one page of results both the next and previous links would appear but in a disabled state (unclickable). If we think it makes more sense for them to not appear at all with less than 20 results, let me know and I can update.

**Comment by kmori** [comment]
> > Should we remove the "Previous" and "Next" when there's only one page worth of results?
> 
> @kmori We could, although I believe with just one page of results both the next and previous links would appear but in a disabled state (unclickable). If we think it makes more sense for them to not appear at all with less than 20 results, let me know and I can update.

@lauraponce- any thoughts from a UX perspective of if we should keep the "Previous" / "Next" in a disabled state when there's only one page of search results or remove it?

**Comment by lauraponce** [comment]
I think it would be better to remove them rather than keep the links there and disabled since it might not seem clear to people why the links are disabled.

Is it possible to add the `pages 1/1` at the bottom near the buttons to show how many pages of results there are? (This also is out of scope from this ticket so it shouldn't hold up this one from closing and could go in another one if needed.)

**Comment by kmori** [comment]
thanks @lauraponce ! @hursey013 - can we remove the links when there's only one page of results. I'll also make a new ticket for the recommendation provided above re number of pages

**Pull request merged**
