### PR TITLE
T3 regs

### PR DESCRIPTION
**Pull request by c2nelson**
Title III Regs drafted

### CODE REVIEW

**Comment by vwilliamsn** [comment]
@c2nelson - It's looking really good! 

A few issues are coming up throughout the document: 
- spacing issues, the words are running together (in some places) if you do ctrl F and type in "_See_" that a good place to check many of the spacing issues.
- there is also an issue around some of the ()'s too (look at the beginning of each paragraph (A) or (ii)

- this issue is hard to explain, it might be helpful to use the [link document](http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/ADA/2010%20Regulations%20(T2%20%26%20T3)/CINDY%20Americans%20with%20Disabilities%20Act%20Title%20III%20Regulations%2010_27_22.docx?d=we21ce7a577df4b3db47b1c9373f53639) as a reference, I started to highlight and add comments to remove the * for some reason they appear in random places. (Sidebar: keep the * when they appear in threes (***), remove the others.

Happy to chat if you have questions.

**Comment by vwilliamsn** [comment]
11/3 update: @c2nelson some additional edits (this should be the last round): 

- remove special function and separate (3) from the body of (2):
image

- fix spacing issues:
image

- check the font size for the H3 headers (it seems really small (it could just be me and the font size is okay too)) in the Section-to-Section Analysis and Responses to Comments
image
image

- I flag this in my last round of edits (picture better than my explanation). Fix spaces, remover * and check font size for the H3 headings
image
image

**Comment by vwilliamsn** [comment]
@c2nelson thanks for all your work on this! We have one issue remaining then we can get this approved.  

Throughout the document there are some random "*".

I provided some examples in my last comment. Apologies as I struggled to explain what I saw.  The best way to catch them in the doc is "control F" and in the search box type * and do the same for the original T3 reg and you can see where they belong/don't belong.

**Comment by vwilliamsn** [comment]
11/5 - @c2nelson - I have access to github on my iPhone, so just let me know when the changes are done, and I will approve this ticket. Thanks!

**Comment by c2nelson** [comment]
@JackRyan1989 the anchors in T2 and T3 check out.  Thanks!

**Review by vwilliamsn — APPROVED** [review]
Great job @c2nelson!

**Pull request merged**
