### PR TITLE
Remove homepage image credits in footer from non-homepage pages

### PR DESCRIPTION
**Pull request by JackRyan1989**
We only use images from Unsplash on the homepage. We only use images from Adobe stock images on our Topics pages. We want to make sure that the footer text aligns properly with the images being used. 

Changes:

1.  Added some conditional logic to the footer.html file to toggle between the different image attribution text depending on the page.

Test:

1.  Check that the attribution text is correct when on the homepage (Unsplash) and on any topics page (Adobe stock photos).
2.  Make sure that no attribution text appears on pages without any images.

### CODE REVIEW

**Review by chinelo-ikejimba — CHANGES_REQUESTED** [review]
@JackRyan1989 - Sharing the [ADA Style Guide](https://www.figma.com/file/yKSv3BjDc9d0rXEe99bjoB/CRT-and-ADA-Styles-Guide_June2021?node-id=0%3A1886) 18F created for reference.

Please update the following:

**Homepage** (for desktop & mobile)
- [Adobe Stock](https://stock.adobe.com/)
- [Disabled and Here photo collection](https://affecttheverb.com/gallery/disabledandhere/whitewalllean/)

**Topics**
- Could we hide the Image Attribution footer on the [individual Topics pages](https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/image-credits-438/topics/parking/) since they don't show Adobe Stock images?
- The Topics landing page is perfect as is.

**Comment by JackRyan1989** [comment]
@chinelo-ikejimba Your changes have been addressed.

**Review by chinelo-ikejimba — CHANGES_REQUESTED** [review]
@JackRyan1989 please remove the "Unsplash: Jon Tyson" link from the homepage footer and it's good to go 🙏🏽

Screen Shot 2022-04-21 at 11 59 56 AM

**Review by chinelo-ikejimba — APPROVED** [review]
🙌🏽

**Pull request merged**
