### PR TITLE
Best bet box styling

### PR DESCRIPTION
**Pull request by kewitham**
This PR updates the styling for the search result best bet boxes.
[Figma](https://www.figma.com/file/2BtQC1OVFFWm1bVLCxW7HL/ADA.gov---2023?node-id=2263%3A26467&t=eQTNoqmfFFQMvCBp-0)

- 🌎 The current ADA.gov best bet results are styled the same as the other results (red annotation added by me):
image
- ⛔ There is no indication that the top result of the above search is the one recommended by the ADA
- ✅ This PR styles the search best bet boxes to differentiate them from the other results.
- 🔮 Currently there is only one best bet result specified (the one pictured above for the query "Americans with Disabilities Act") but more will be added for common search terms.

Screenshot (1)

### CODE REVIEW

**Review by okkays — APPROVED** [review]
🎉

**Comment by nguyen-tina** [comment]
Looking great, Katie! After seeing it, I think we should make the following changes:

- [ ] We should actually have 'Recommended by ADA.gov' as the title for the section within the blue lines
- [ ] The italicized title underneath that larger section title should be the pre-determined section title for whatever group of Search results are set aside for each topic section. Generally, I think they should correspond with the Featured Topics on the site

Also, I realize that we don't have a place where we show the user the input that they used to get their search results. That should definitely be there. Should this be a separate ticket? If you can include it in this one, that'd be great. The update to the design would be as follows: append 'for 'SEARCH TERM HERE'' to the existing text under Search. See below!

BBB - phone

**Comment by nguyen-tina** [comment]
Confirming decision made on 2/25/23 coworking – that we should remove the small italicized title of the section, as there's no way for us to input that information for Best Bet boxes

**Comment by vwilliamsn** [comment]
> Confirming decision made on 2/25/23 coworking – that we should remove the small italicized title of the section, as there's no way for us to input that information for Best Bet boxes

@nguyen-tina - are you referring to this small, italicized, title of the section? 
[image](https://user-images.githubusercontent.com/96496943/221992046-a5f8e2cb-b0ac-4c9e-96b6-385313c1f652.png)

**Comment by nguyen-tina** [comment]
> > Confirming decision made on 2/25/23 coworking – that we should remove the small italicized title of the section, as there's no way for us to input that information for Best Bet boxes
> 
> @nguyen-tina - are you referring to this small, italicized, title of the section? [image](https://user-images.githubusercontent.com/96496943/221992046-a5f8e2cb-b0ac-4c9e-96b6-385313c1f652.png)

yes, that's correct!

**Review by nguyen-tina — COMMENTED** [review]
This is looking good, though I would have the two Best Bet columns stack vertically on top of each other at any screen size smaller than a tablet.

**Comment by kewitham** [comment]
> > > Confirming decision made on 2/25/23 coworking – that we should remove the small italicized title of the section, as there's no way for us to input that information for Best Bet boxes
> > 
> > 
> > @nguyen-tina - are you referring to this small, italicized, title of the section? [image](https://user-images.githubusercontent.com/96496943/221992046-a5f8e2cb-b0ac-4c9e-96b6-385313c1f652.png)
> 
> yes, that's correct!

This has been removed.

**Comment by nguyen-tina** [comment]
This looks good to me, thanks for making those changes Katie!

**Comment by nguyen-tina** [comment]
cc @vwilliamsn and @c2nelson for review

**Review by vwilliamsn — APPROVED** [review]
Thanks @nguyen-tina and @kewitham!

**Review by c2nelson — APPROVED** [review]

**Pull request merged**
