### PR TITLE
Merge into Main on Launch Day

### PR DESCRIPTION
**Pull request by JackRyan1989**
Current branches merged in and complete:

1. jr/add-archive-link-to-footer
2. jr/add-ada-to-ada-redirects
3. jr/ta-archive-notice
4. jr/search-page-text
5. jr/remove-beta - NOTE: For redirect testing the site.url value has been commented out. It must be uncommented to be pushed live!

To Merge in:

1. jr/update-search-params
2. jr/replace-ada-links-with-archive
3. ADA Banner Notifications

### CODE REVIEW

**Comment by billyhunt** [comment]
https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/ada-main/medcare_mobility_ta/medcare_ta.pdf is also returning a "Failed to load PDF document" error.

**Comment by billyhunt** [comment]
Same with 
https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/ada-main/service_animals_2010.pdf

**Comment by billyhunt** [comment]
https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/ada-main/adastd94.pdf

**Comment by vwilliamsn** [comment]
Great job @JackRyan1989 & @c2nelson the site looks great! 
 
Please add the PDF versions of the design standard and guidance?

**Comment by billyhunt** [comment]
I have looked at rows 500-800 here.  https://docs.google.com/spreadsheets/d/1MJcF9Ewp3nuepwxErw5V2TrgGTM5DPZC/edit#gid=1013101708

Everything looks great.

**Comment by billyhunt** [comment]
I did 800-the end.  No problems!  Well done!

**Review by vwilliamsn — APPROVED** [review]
Thanks @JackRyan1989!

**Pull request merged**
