### PR TITLE
added proposed chgs content

### PR DESCRIPTION
**Pull request by c2nelson**
Also added proposed changes content to regs landing page

### CODE REVIEW

**Comment by vwilliamsn** [comment]
@c2nelson - the Federalist link is giving a 404 error. 404 Not Found: Requested route ('federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov') does not exist.

**Comment by okkays** [comment]
@c2nelson Does this link work (from pages/build Details)? https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.sites.pages.cloud.gov/preview/usdoj-crt/beta-ada/proposed-regs-content/

**Comment by c2nelson** [comment]
@okkays yes

**Review by vwilliamsn — APPROVED** [review]
LGTM! Thanks @c2nelson and @okkays!

**Pull request merged**
