### PR TITLE
Add Touchpoints snippet

### PR DESCRIPTION
**Pull request by hursey013**
Fixes https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/144

### CODE REVIEW

**Comment by colinmurphy01** [comment]
Getting an error upon form submission that it's from an unauthorized host. Is this a known issue?
Screen Shot 2021-05-19 at 8 43 45 AM

**Comment by colinmurphy01** [comment]
@hursey013 Can we have the global nav and homepage button bring up the modal, similar to the experience of the button at the bottom of the browser? I'd prefer to not take them to another page.

**Comment by hursey013** [comment]
@colinmurphy01 Setting the authorized host is done within the Touchpoints website - I've updated it to match the Federalist preview links, however it will need to be changed once the website is being served on the subdomain.

Updated links to launch modals.

**Comment by colinmurphy01** [comment]
Thank you for updating and allowing me to test the full submission flow. Confirmed that everything is working as expected.

I am noticing a weird issue with the alert box icons in the error screen and success screen. Any thoughts on that?
Screen Shot 2021-05-19 at 4 46 34 PM
Screen Shot 2021-05-19 at 8 43 45 AM

@hursey013 @c2nelson I don't know if there is a queue for Terri's review or if someone is actively managing that, but I'd be interested in adding this for the next session with her.

**Comment by hursey013** [comment]
@colinmurphy01 looks like Touchpoints is including some non-namespaced USWDS CSS classes, so the styles are conflicting. Got it cleaned up a bit: 

Screen Shot 2021-05-20 at 10 27 29 AM

**Comment by hursey013** [comment]
Waiting on clarification from https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/144

**Comment by hursey013** [comment]
@colinmurphy01 re:accessibility - I think it could be helpful to have Terry check it out, but just want to point out that we are unable to modify any of the code associated w/ Touchpoints, so any issues she discovers would need to be addressed by the Touchpoint folks.

**Comment by hursey013** [comment]
Updated based on feedback from https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/144#issuecomment-845425602

**Pull request merged**
