### PR TITLE
Update Design Standards “2010-stds”

### PR DESCRIPTION
**Pull request by vwilliamsn**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by vwilliamsn** [comment]
Request to make 2 small edits to the 2010 Design Standards. Here's a copy of the request:

"Today, I came across needed edits in Section 106 Definitions.  The definitions of “Curb Ramp” and “Detectable Warning” have a formatting issue that makes them one definition instead of two definitions.  In addition, the text “Detectable Warning.” is not bolded as the other defined terms are in this section."

Would it possible to make these edits?

**Comment by vwilliamsn** [comment]
I made the requested edits via Netlify and now those edits are pending review before they can be merged and published.

@kewitham - I was able to make the edits, however, the side preview panel has an error message. https://www.ada.gov/admin/#/collections/design-standards/entries/2010-stds?ref=workflow

**Review by kewitham — APPROVED** [review]
lgtm!

**Comment by kewitham** [comment]
> I made the requested edits via Netlify and now those edits are pending review before they can be merged and published.
> 
> @kewitham - I was able to make the edits, however, the side preview panel has an error message. https://www.ada.gov/admin/#/collections/design-standards/entries/2010-stds?ref=workflow

It looks like Netlify is having an issue rendering one of the components but when I check the Federalist preview it looks correct 👍

**Pull request merged**
