### PR TITLE
Use pa11y-ci

### PR DESCRIPTION
**Pull request by hursey013**
The starter template we are using relies on https://github.com/addyosmani/a11y which is no longer maintained and has not been updated in over four years. This integrates a new a11y CI tool, `pa11y-ci` which is more actively developed and provides additional configuration options that will be helpful in this project.

Lastly, reports of a11y results are now generated for each push and are currently available as an artifact, such as: https://131-346501322-gh.circle-artifacts.com/0/pa11y-results/index.html - this provides a great visual to any a11y issues as opposed to the normal terminal output. In a future PR I would like to find a way to pull this report in as a status check so it's easily accessed for all new pull requests.

### CODE REVIEW

**Comment by hursey013** [comment]
The failing CircleCI test is expected since we have some issues in the current beta site.

**Review by brentryanjohnson — APPROVED** [review]

**Comment by brentryanjohnson** [comment]
@hursey013 I'm getting npm errors locally when running either `npm run test` or `npm start`. 

```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! federalist-uswds-jekyll@1.3.0 pa11y:json: `pa11y-ci --json --sitemap http://127.0.0.1:4000/sitemap.xml > ./pa11y-ci-results.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the federalist-uswds-jekyll@1.3.0 pa11y:json script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
ERROR: "pa11y:json" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! federalist-uswds-jekyll@1.3.0 test: `npm-run-all --continue-on-error --serial start:detach pa11y:json pa11y:save`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the federalist-uswds-jekyll@1.3.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by brentryanjohnson** [comment]
Interesting...is it possible there are commands trying to use the same port simultaneously? It looks like that might have something to do with it, but even when I shut down the terminal and run it again, I get the same error.

I was able to get local dev running again by passing in a different port: `bundle exec jekyll serve --watch --port 4444', but couldn't get it running with `npm start`.

**Comment by hursey013** [comment]
@brentryanjohnson yeah, good call. I was focused on getting it to work in the CI env and less on local which made things a bit confusing. Since we don't need to generate the HTML report or start up a detached server locally, I split out that stuff out into a separate `test:ci` npm script, and left `npm test` to just run pa11y against a locally running server and return the results in the terminal.

**Comment by colinmurphy01** [comment]
This is so dope.

A couple questions for awareness:
- Was scrolling through the [audit rules](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules), curious do we know if it adheres to a certain level of accessibility standards (A, AA, AAA)?
- When do you see this job running - when code is pushed to any branch?
- How long does the job take?
- How long are the reports hosted and maintained?

**Comment by hursey013** [comment]
@colinmurphy01
> * Was scrolling through the [audit rules](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules), curious do we know if it adheres to a certain level of accessibility standards (A, AA, AAA)?

I've configured it to adhere to WCAGAA https://github.com/usdoj-crt/beta-ada/pull/59/files#diff-a60a1c153f415927c8e32e9e6e0f881805b853f2a67195a2036f4813cc6fa919R4

> * When do you see this job running - when code is pushed to any branch?

It will run on every push - right now you would need to go to CircleCI to see the generated report, but looking into a way to bring that link directly into the pull request view.

> * How long does the job take?

Last run took `58s` https://app.circleci.com/pipelines/github/usdoj-crt/beta-ada/132/workflows/aaddef9f-f59b-45b1-8a6f-7bd37dd0976a/jobs/132 - however that is using about a dozen pages of dummy content, this time will increase as more pages/content is added.

> * How long are the reports hosted and maintained?

30 days

**Review by brentryanjohnson — APPROVED** [review]

**Pull request merged**
