### PR TITLE
Netlify Integration

### PR DESCRIPTION
**Pull request by billyhunt**
Add Netlify CMS to ADA.

### CODE REVIEW

**Comment by billyhunt** [comment]
@JackRyan1989, I am getting a required field error when trying to save to the index page.

image

Should news be required?

**Comment by JackRyan1989** [comment]
@billyhunt Good catch. Yeah, the News text should be required. It's the text for that section that displays when there are news items. Just wondering, but was there text in there already?

**Comment by billyhunt** [comment]
It was not!

**Comment by JackRyan1989** [comment]
@billyhunt Found the problem! The name field for the News widget was set to "News" instead of "news"

**Comment by billyhunt** [comment]
Nice one!

**Review by JackRyan1989 — APPROVED** [review]
Looks good to me!

**Pull request merged**
