### PR TITLE
Download PDF button 447

### PR DESCRIPTION
**Pull request by JackRyan1989**
Rationale:
We want to provide a quick way for users to download available pdfs as pdfs without needing to print or save them. In this PR we are creating a new includes component that takes an input pdf name and title and generates an anchor link in a div wrapper. The name is necessary to associate the link with the pdf document to download, and the title attribute is necessary to display the name/title of the pdf the person is downloading. 
Note pdfs need to be stored within the /pdfs/ folder in the main beta-ada directory. That directory path is hard coded into the component. 

Changes:
1. /_includes/download-pdf.html - the component
2. /_pdfs/ - the location where new pdfs need to be stored
3. For demonstration/testing purposes the component is being called into the /web-guidance.md/ file. 
4. _config.yml - the assets raw-precompile step now includes the _pdfs directory so that pdfs are pulled into the /assets folder at build time. 

Desktop:
Screen Shot 2022-04-25 at 2 44 36 PM

Mobile:
Screen Shot 2022-04-25 at 2 44 54 PM

### CODE REVIEW

**Review by chinelo-ikejimba — CHANGES_REQUESTED** [review]
@JackRyan1989 @c2nelson 

After reading the feedback Veronica shared via email and checking out the Federalist preview for Download PDF, I recommend replacing the "Print this page" button with the "Download PDF" in the sidebar nav.

This way there's only 1 call-to-action (CTA) button for producing a hardcopy beta page and it's conveniently located in the sidebar nav with the following logic:

- If a PDF exists, then button = Download PDF
- If a PDF doesn't exist, then button = Print this page

**Comment by JackRyan1989** [comment]
> @JackRyan1989 @c2nelson
> 
> After reading the feedback Veronica shared via email and checking out the Federalist preview for Download PDF, I recommend replacing the "Print this page" button with the "Download PDF" in the sidebar nav.
> 
> This way there's only 1 call-to-action (CTA) button for producing a hardcopy beta page and it's conveniently located in the sidebar nav with the following logic:
> 
> * If a PDF exists, then button = Download PDF
> * If a PDF doesn't exist, then button = Print this page

@chinelo-ikejimba So I have this configured to work as described, but I'm wondering how this will work for pages that have multiple pdfs, like the design standards page?

**Comment by JackRyan1989** [comment]
@chinelo-ikejimba Ok, I added the constraint that will make the button look like a hyperlink if the text content exceeds 26 chararcters. Here are some images:

**Button:**
Desktop:
Screen Shot 2022-04-25 at 4 55 16 PM

Mobile sidenav:
Screen Shot 2022-04-25 at 5 00 41 PM

Mobile main content:
Screen Shot 2022-04-25 at 5 00 54 PM

**Hyperlink:**
Desktop:
Screen Shot 2022-04-25 at 4 52 26 PM

Mobile:
Screen Shot 2022-04-25 at 4 55 05 PM

**Review by chinelo-ikejimba — APPROVED** [review]
@JackRyan1989 thanks for showing the examples of the call-to-action as a hyperlink when the text exceeds the character limit.

Looks good to go

**Pull request merged**
