### PR TITLE
2010 Title II regulations

### PR DESCRIPTION
**Pull request by JackRyan1989**
This is a new page. It brings over the content from the Title II 2010 Regulations on ada.gov to beta. 

@c2nelson where is this page going in the content structure?

### CODE REVIEW

**Comment by c2nelson** [comment]
@JackRyan1989 it will link from the reg landing page under "what is a reg" and i think the file itself can live in the root - law-and-regs

**Comment by vwilliamsn** [comment]
Thanks for your work on the @JackRyan1989 - YOU ROCK!  The federalist link isn't working for me, I'm unable to review your great work.

**Comment by JackRyan1989** [comment]
@vwilliamsn Thanks for catching that! It is fixed: https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/jr/2010-title-2-regulations/law-and-regs/title-ii-2010-regulations/

**Comment by vwilliamsn** [comment]
Hey @JackRyan1989 - can you please add the print button?  Thanks!

**Comment by JackRyan1989** [comment]
@vwilliamsn Print button has been added! Since this is a long page, I suggest we add the back to top button and the nested subnavigation, especially since the side nav is so long.

**Comment by vwilliamsn** [comment]
Hey @JackRyan1989 - thanks so much for your work on this, it's looking good. I made edits and comments in the document. Somethings have explanations; others just have corrections. Happy to chat if you have any questions.

Here are my edits: http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/ADA/2010%20Regulations%20(T2%20%26%20T3)/JACK_Americans%20with%20Disabilities%20Act%20Title%20II%20Regulations.docx?d=we68508eb7ca642b3ae79bc351557f989

**Comment by vwilliamsn** [comment]
> @vwilliamsn Thanks for the feedback!
> 
> I have a few statements.
> 
> 1. The headers you highlighted as needing consistent styling are all the same. They're all H2s, and as such are styled the same. I'm not sure if you don't want them styled that way or if you'd prefer them styled some other way?
> 2. If we keep the bullets we cannot left align. The left padding on bulleted items is consistent across the site, and I don't want to alter the styling in one small case.

1) Okay, maybe there was something wacky going on when I went through the document.  IF they are all the same, great! 
2) I think there's only one place where bullets are required, we can keep them there (don't worry about left aligning).

**Comment by JackRyan1989** [comment]
@vwilliamsn Thanks! This is ready for re-review

**Comment by vwilliamsn** [comment]
@JackRyan1989 - I went back through the document and highlighted the changes that might have been missed as they are small things that are in paragraph changes like: spacing issues, misspelled words, italic, bold, etc.  

So, please go back through the document looking for the things that I highlighted and make the appropriate changes (if needed).  Happy to chat if you have any questions. Thanks!

**Comment by JackRyan1989** [comment]
@vwilliamsn  I have addressed the latest round of edits! Thanks!

**Comment by vwilliamsn** [comment]
@JackRyan1989 these should be the last few changes:

Find all the locations in the document that mention the **Federal Register** - there is some type of spacing issue.  All of the words around Federal Register run together.

And in § 35.137 Mobility devices (c)(1) remove </p>

Lastly, after launch we may revisit this document to make it more visually appealing, I feel like the words all run together. Happy to chat if you have any recommendations.

**Comment by JackRyan1989** [comment]
@vwilliamsn Ok, I addressed your above changes. Please let me know if you're ok with me requesting Terrie's review on this. And yeah, I'm not exactly sure what we can do about the readability of the text, @beckyslogeris may have some ideas though...

**Pull request closed without merging**
