### PR TITLE
Added new text and formatting for file a complaint copy

### PR DESCRIPTION
**Pull request by JackRyan1989**
1. Changes:
- Added new text to the file a complaint page
- Added styling to match @chinelo-ikejimba's designs
- Did my best to match the text in presente una queja page.

2. Test:
- Confirm that the page in the preview link matches the design mockup provided by Chinelo
- Confirm that the Spanish language page matches the styling

[Here is the mockup](https://user-images.githubusercontent.com/92807659/159792573-e2fc137e-00df-405b-bd24-f44b0dd3f4b7.png)

### CODE REVIEW

**Review by c2nelson — COMMENTED** [review]
thanks, jack.  looks good.

**Comment by vwilliamsn** [comment]
great job...thanks everyone!

**Review by chinelo-ikejimba — CHANGES_REQUESTED** [review]
Nice, it's coming together.

Can these changes be added in?

1. Ordered list header typography changed to Merriweather, font color #162E51.
2. Add 1 line spacing between items 1 and 2 to give space between their sections.

Reference: [filing a complaint with the DOJ design handoff](https://www.figma.com/file/ouOsvcXGkJ8LAh1RoIPMY2/ADA.gov-Designs-and-Handoff?node-id=637%3A17268)

**Comment by JackRyan1989** [comment]
> Nice, it's coming together.
> 
> Can these changes be added in?
> 
> 1. Ordered list header typography changed to Merriweather, font color #162E51.
> 2. Add 1 line spacing between items 1 and 2 to give space between their sections.
> 
> Reference: [filing a complaint with the DOJ ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/416#issuecomment-1076793873)

Hey @chinelo-ikejimba do you want all ordered lists to have that styling applied or only the one on the File a Complaint page? Because we have other ordered lists on the [/mobility-devices](https://beta.ada.gov/topics/mobility-devices/) and [/law-and-regulations](https://beta.ada.gov/law-and-regs/) pages.

**Comment by chinelo-ikejimba** [comment]
> > Nice, it's coming together.
> > Can these changes be added in?
> > 
> > 1. Ordered list header typography changed to Merriweather, font color #162E51.
> > 2. Add 1 line spacing between items 1 and 2 to give space between their sections.
> > 
> > Reference: [filing a complaint with the DOJ ticket](https://github.com/usdoj-crt/beta.ADA.gov-Project-Management/issues/416#issuecomment-1076793873)
> 
> Hey @chinelo-ikejimba do you want all ordered lists to have that styling applied or only the one on the File a Complaint page? Because we have other ordered lists on the [/mobility-devices](https://beta.ada.gov/topics/mobility-devices/) and [/law-and-regulations](https://beta.ada.gov/law-and-regs/) pages.

@JackRyan1989 - Not all ordered lists but only ordered lists with section headings. It's a similar styling I created for the Portal's html email like the image below
Yes typography

**Review by chinelo-ikejimba — APPROVED** [review]
Good to go!

**Pull request merged**
