### PR TITLE
2010 Design Stds

### PR DESCRIPTION
**Pull request by c2nelson**
initial build - work in progress

### CODE REVIEW

**Comment by c2nelson** [comment]
url - https://federalist-1716bf9c-dd79-4d96-8285-6e56dc391b84.app.cloud.gov/preview/usdoj-crt/beta-ada/design-stds/law-and-regs/design-standards/2010-stds/

**Comment by vwilliamsn** [comment]
@c2nelson - great job on this document. I've made some small edits up through chapter 3, here's the link if you want to get started: 

http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/ADA/Design%20Standards/Cindy%202010%20Design%20Standards.docx?d=w567ba7474db64624a80741ca7b5f62ea

**Comment by vwilliamsn** [comment]
@c2nelson - great job on this document. I'm done my review, I tried to highlight every place where I requested/made changes.  Let me know if you have any question.

**Review by vwilliamsn — APPROVED** [review]
Great job @c2nelson!

**Review by vwilliamsn — APPROVED** [review]
Great job @c2nelson!

**Review by JackRyan1989 — APPROVED** [review]

**Comment by JackRyan1989** [comment]
@c2nelson can you check all of the links to the 2010 Standards? There are a bunch in the Title II and III primers, the parking documents and in the 2010 and 1991 standards themselves. I saw no links to the 91 standards. Can you double check?

**Comment by c2nelson** [comment]
@JackRyan1989 the links to the standards all seem to be checking out.  links to the  t2 and t3 primers on the parking overlay need to be changed though (to the modern site)

**Comment by JackRyan1989** [comment]
@c2nelson I'll make the changes to the parking overlay and push those back up. Thanks for checking!

**Pull request merged**
